openapi: '3.0.3'
info:
  title: Timeline Spec
  version: '1.0'
servers:
  - url: https://friendpost/v1/timeline
    description: API to use timeline

components:
  schemas:
    Post:
      type: object
      required:
        - userId
        - data
        - createdAt
        - updateAt
      properties:
        userId:
          type: string
          description: Unique ID for each User
        userName:
          type: string
          description: User Name for the User ID
        content:
          type: string
          description: Text data posted by userId
        postId:
          type: string
          description: Id of the Post
        createdAt:
          type: string
          description: Time at which post was created
        updatedAt:
          type: string
          description: Time at which post was created

paths:
  /timeline/{userId}:
    get:
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      summary: Retrieve a list of posts from public and friends
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
        '404':
          description: User Not Found
        '500':
          description: Internal Server Error
              
