openapi: '3.0.3'
info:
  title: Timeline Spec
  version: '1.0'
servers:
  - url: https://friendpost/v1/timeline
    description: API to use timeline

components:
  schemas:
    Post:
      type: object
      required:
        - userId
        - data
        - createdAt
        - updateAt
      properties:
        userId:
          type: string
          description: Unique ID for each userId
        content:
          type: string
          description: Text data posted by userId
        createdAt:
          type: string
          description: Time at which post was created
        updatedAt:
          type: string
          description: Time at which post was created

paths:
  /timeline/{id}:
    get:
      summary: Retrieve a list of posts from public and friends
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
              
